#!/bin/bash

if [[ 
    -z "$1" || 
    "$1" =~ -. ||
    -z "$2" || 
    "$2" =~ -.
]]; then
    echo "Usage: $(basename $0) [FILE_NAME] [FILE_NAME] [THRESHOLD]"
    exit -1
fi

THRESHOLD=${3:-80}
TEMP1=.temp1
TEMP2=.temp2

sed '/^$/d' "$1" > $TEMP1
sed '/^$/d' "$2" > $TEMP2

DIFF=$(sdiff -bBs $TEMP1 $TEMP2 | wc -l)
SIZE1=$(cat $TEMP1 | wc -l)
SIZE2=$(cat $TEMP2 | wc -l)
MAX_SIZE=$(( $SIZE1 > $SIZE2 ? $SIZE1 : $SIZE2 ))
rm $TEMP1 $TEMP2

DIFF_PERCENTAGE=$(echo "scale=2;($MAX_SIZE-$DIFF)/$MAX_SIZE" | bc | sed 's/\.//g')

if [ $DIFF_PERCENTAGE -ge $THRESHOLD ]; then
    echo "$2 is duplicate of $1"
else
    echo "$2 is not duplicate of $1"
fi
