#!/bin/bash

FLAGS=""
INTEL_BUILD=""
SHOULD_CLEAN=""

for flag in "$@"; do
    if [[ $flag == *"r"* ]]; then
        FLAGS="${FLAGS} --repo-update"
    fi
    if [[ $flag == *"c"* ]]; then
        SHOULD_CLEAN=1
        FLAGS="${FLAGS} --clean-install"
    fi
    if [[ $flag == *"v"* ]]; then
        FLAGS="${FLAGS} --verbose"
    fi
    if [[ $flag == *"i"* ]]; then
        INTEL_BUILD="arch -x86_64"
    fi
done

if [[ $SHOULD_CLEAN -eq 1 ]]; then
    podclean
    echo 
fi

set -x

$INTEL_BUILD pod install $FLAGS