#!/opt/homebrew/bin/bash

FLAGS=""
INTEL_BUILD=""

for flag in "$@"; do
    case $flag in
        *r*)
            FLAGS="${FLAGS} --repo-update";;&
        *c*)
            podclean && echo
            FLAGS="${FLAGS} --clean-install";;&
        *v*)
            FLAGS="${FLAGS} --verbose";;&
        *i*)
            INTEL_BUILD="arch -x86_64";;
    esac
done

set -x

$INTEL_BUILD pod install $FLAGS
